### ISSUE TITLE
Solenoid Work 

### ISSUE THREAD

**Issue by VayunT** [Team293/ChargedUp#12]
We need to find 2023 code for Solenoids and learn about them for Megan and Cole's prototype.

**Comment by LavaWaffle** [comment]
Also need to work with a color sensor to decide which Solenoid to activate based on the held game piece.

**Comment by bjmcternan** [comment]
Is this feature still needed? Close this if it was cut @VayunT

**Comment by PranjalMhetre** [comment]
not being used anymore
