### ISSUE TITLE
Add joystick controls to x-box controls for arm

### ISSUE THREAD

**Issue by GoldCrafter** [Team293/ChargedUp#29]
Add joystick controls so we are able to use both x-box controls and joystick control to control the arm.

**Comment by bjmcternan** [comment]
Is this referring to the adjust arm command? Aren't we doing that already?

**Comment by KinuTheDragon** [comment]
It is referring to the AdjustArm command, yes

**Comment by GoldCrafter** [comment]
We're adding controls for Logitech joysticks.
